// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package dao

import (
	"database/sql"
	"time"
)

type Element struct {
	ID     string
	JpName string
	EnName string
}

type Guild struct {
	ID   string
	Name sql.NullString
}

type GuildMember struct {
	ID       int32
	GuildID  string
	HunterID string
	NickName sql.NullString
}

type Hunter struct {
	ID          string
	Name        string
	DisplayName sql.NullString
}

type Monster struct {
	ID           string
	JpName       string
	EnName       string
	Discoverable bool
}

type PaintedMonster struct {
	ID          int32
	Rank        int16
	HunterID    string
	MonsterID   string
	DisappearAt time.Time
	Location    sql.NullString
}
